/**
 * `noa.action-digest/0.1` — the committed conformance corpus, plus the properties the corpus alone
 * cannot state.
 *
 * THE CORPUS (conformance/action-digest/vectors.json) is generated by
 * `scripts/gen-action-digest-vectors.ts` from REAL seeded Ed25519 keys, so every rejection vector is
 * a cryptographically well-formed document that fails a SEMANTIC rule — never a broken blob. Each
 * vector pins its refusal REASON, not just `ok:false`: a negative that passes because some earlier
 * check happened to fire is a negative that measures nothing, and the reason string is what
 * distinguishes the two.
 *
 * THE EXTRA PROPERTIES here are the ones a fixture cannot express:
 *   - CROSS-PACKAGE PARITY. `executionGrantHash` restates the F1 rule-b convention that lives in
 *     `packages/approval-artifacts/src/refhash.ts`. A restatement without a gate is drift waiting to
 *     happen, so the rule is measured against that package's OWN committed vector — the
 *     `grantHash` inside `conformance/execution-consumption/valid.json`, produced by its `refHash`.
 *   - SCHEMA PARITY. The grant key list this module enforces is measured against the shipped
 *     `noa-execution-grant-0.1.schema.json` `required` list, so a schema change breaks this test
 *     rather than silently splitting two definitions of a valid grant.
 *   - PROJECTION KNOCKOUT. Every field of the frozen projection is removed, one at a time, and the
 *     digest must change. A field that can be deleted without moving the digest is not in the
 *     construction at all.
 *   - DETERMINISM. The same inputs digest identically across calls and across key orderings.
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  ACTION_DIGEST_DOMAIN,
  ACTION_DIGEST_SPEC,
  buildActionDigest,
  verifyActionDigest,
} from "../src/action-digest.js";
import { canonicalize } from "../src/jcs.js";
import { sha256Prefixed } from "../src/hash.js";
import { signingMessage } from "../src/signing.js";
import { receiptHashInput } from "../src/canonicalize.js";
import { buildReceipt } from "../src/builder.js";
import { generateKeyPair } from "../src/keys.js";
import { verifyChain } from "../src/verify.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..", "..");

interface Vector {
  name: string;
  note: string;
  /** JSON claim document; mutually exclusive with `claimText`. */
  claim?: unknown;
  /** Literal bytes for the claim (used by the malformed-input vectors). */
  claimText?: string;
  context?: unknown;
  contextText?: string;
  expect: { ok: boolean; reasonContains?: string; digest?: string };
}

interface Corpus {
  spec: string;
  domain: string;
  generatedFrom: string;
  vectors: Vector[];
}

const corpus = JSON.parse(
  readFileSync(join(ROOT, "conformance", "action-digest", "vectors.json"), "utf8"),
) as Corpus;

const bytesOf = (vec: Vector, which: "claim" | "context"): string => {
  const literal = which === "claim" ? vec.claimText : vec.contextText;
  if (typeof literal === "string") return literal;
  return JSON.stringify(which === "claim" ? vec.claim : vec.context);
};

test("the corpus is the shape the runner expects and is non-trivial", () => {
  assert.equal(corpus.spec, ACTION_DIGEST_SPEC);
  assert.equal(corpus.domain, ACTION_DIGEST_DOMAIN);
  const accepts = corpus.vectors.filter((v) => v.expect.ok).length;
  const rejects = corpus.vectors.length - accepts;
  assert.ok(accepts >= 1, `expected ≥1 ACCEPT vector, found ${accepts}`);
  assert.ok(rejects >= 12, `expected ≥12 REJECT vectors, found ${rejects}`);
  // Every rejection must pin its reason. Without this, a vector can pass by tripping the wrong rule.
  for (const v of corpus.vectors) {
    if (!v.expect.ok) {
      assert.equal(typeof v.expect.reasonContains, "string", `${v.name}: rejection vector must pin a reason`);
      assert.ok((v.expect.reasonContains as string).length > 0, `${v.name}: empty reason`);
    }
  }
});

for (const vec of corpus.vectors) {
  test(`action-digest/${vec.name} → ${vec.expect.ok ? "ACCEPT" : "REJECT"}`, () => {
    const res = verifyActionDigest(bytesOf(vec, "claim"), bytesOf(vec, "context"));
    assert.equal(res.ok, vec.expect.ok, res.ok ? "expected a refusal" : `unexpected refusal: ${res.reason}`);
    if (!res.ok) {
      assert.ok(
        res.reason.includes(vec.expect.reasonContains as string),
        `${vec.name}: refused for the WRONG reason.\n  got:      ${res.reason}\n  expected: contains "${vec.expect.reasonContains}"`,
      );
    } else if (vec.expect.digest) {
      assert.equal(res.digest, vec.expect.digest);
    }
  });
}

/** The valid vector's two source documents, reused by the property tests below. */
function validContext(): { receipt: unknown; grant: unknown; expect: { tenant: string; chain: string } } {
  const valid = corpus.vectors.find((v) => v.expect.ok);
  assert.ok(valid, "corpus must contain an ACCEPT vector");
  return valid.context as { receipt: unknown; grant: unknown; expect: { tenant: string; chain: string } };
}

test("cross-package parity: executionGrantHash is the SAME F1 rule-b hash noa-approval-artifacts computes", () => {
  // GROUND TRUTH, not a restatement: this file is produced by that package's own generator, and its
  // `grantHash` is `refHash(grant)` over the grant embedded in the same fixture.
  const consumption = JSON.parse(
    readFileSync(
      join(ROOT, "packages", "approval-artifacts", "conformance", "execution-consumption", "valid.json"),
      "utf8",
    ),
  ) as {
    artifact: { grantHash: string };
    context: { refHashChecks: Array<{ path: string; rule: string; artifact: unknown }> };
  };
  const check = consumption.context.refHashChecks.find((c) => c.path === "grantHash");
  assert.ok(check, "the sibling fixture must bind grantHash");
  assert.equal(check.rule, "side", "grantHash must be an F1 rule-b (side-artifact) reference");
  assert.equal(
    sha256Prefixed(canonicalize(check.artifact)),
    consumption.artifact.grantHash,
    "this module's grant-hash rule has drifted from noa-approval-artifacts' refHash",
  );
});

test("schema parity: the enforced grant key list equals the shipped grant schema's required list", () => {
  const schema = JSON.parse(
    readFileSync(
      join(ROOT, "packages", "approval-artifacts", "schema", "noa-execution-grant-0.1.schema.json"),
      "utf8",
    ),
  ) as { required: string[]; additionalProperties: boolean };
  assert.equal(schema.additionalProperties, false, "the grant schema must stay closed");
  // A grant that satisfies the shipped schema must satisfy this module, and vice-versa. The list is
  // asserted through the module's OWN behaviour: removing any required key must refuse.
  const ctx = validContext();
  for (const key of schema.required) {
    const grant = JSON.parse(JSON.stringify(ctx.grant)) as Record<string, unknown>;
    delete grant[key];
    const res = buildActionDigest(JSON.stringify(ctx.receipt), JSON.stringify(grant));
    assert.equal(res.ok, false, `a grant missing required key "${key}" was accepted`);
  }
  // And an EXTRA key is refused too (additionalProperties:false parity).
  const extra = JSON.parse(JSON.stringify(ctx.grant)) as Record<string, unknown>;
  extra["surprise"] = 1;
  assert.equal(buildActionDigest(JSON.stringify(ctx.receipt), JSON.stringify(extra)).ok, false);
});

test("projection knockout: deleting ANY projection field changes the digest", () => {
  const ctx = validContext();
  const built = buildActionDigest(JSON.stringify(ctx.receipt), JSON.stringify(ctx.grant));
  assert.ok(built.ok, built.ok ? "" : built.reason);
  const projection = built.projection as unknown as Record<string, unknown>;
  const keys = Object.keys(projection);
  assert.equal(keys.length, 10, `the frozen projection is 10 fields; found ${keys.length}: ${keys.join(",")}`);
  const digestOf = (p: unknown): string =>
    sha256Prefixed(signingMessage(ACTION_DIGEST_DOMAIN, canonicalize(p)));
  assert.equal(digestOf(projection), built.digest, "the digest is not the domain-tagged hash of the projection");
  for (const key of keys) {
    const knocked = { ...projection };
    delete knocked[key];
    assert.notEqual(
      digestOf(knocked),
      built.digest,
      `projection field "${key}" can be deleted without moving the digest — it is not in the construction`,
    );
  }
});

/**
 * FIELD DIFFERENTIAL — does each projection slot separate two authorizations that differ ONLY there?
 *
 * This is the honest version of "every field earns its place", and it is worth stating what it does
 * and does not show. `authorizationReceiptHash` and `executionGrantHash` are hashes over WHOLE
 * documents, so between them they already commit to every other slot; the last two rows below prove
 * that by moving a receipt field and a grant field that appear in NO other slot. The middle rows are
 * therefore REDUNDANT BY CONSTRUCTION — they are in the projection because `carlos.md` §3's frozen
 * list prescribes them, and what they buy is that the projection is self-describing: an independent
 * implementer who maps `action.canonical` into the `actionId` slot gets a different digest instead
 * of a lucky agreement. Redundancy stated, not hidden.
 */
test("field differential: each projection slot separates authorizations that differ only there", () => {
  const ctx = validContext();
  const baseDigest = (() => {
    const b = buildActionDigest(JSON.stringify(ctx.receipt), JSON.stringify(ctx.grant));
    assert.ok(b.ok, b.ok ? "" : b.reason);
    return b.digest;
  })();

  type Doc = Record<string, unknown>;
  const clone = (v: unknown): Doc => JSON.parse(JSON.stringify(v)) as Doc;

  /**
   * Apply a receipt mutation and RE-ANCHOR: recompute the receipt's own chain.hash and re-point the
   * grant at it. Signatures are left as-is on purpose — this module verifies none, so re-signing
   * would test the signer rather than the construction.
   */
  function mutated(mutate: (r: Doc, g: Doc) => void): string {
    const receipt = clone(ctx.receipt);
    const grant = clone(ctx.grant);
    mutate(receipt, grant);
    const rehash = sha256Prefixed(receiptHashInput(receipt as never));
    (receipt["chain"] as Doc)["hash"] = rehash;
    if (grant["approvalReceiptHash"] === (clone(ctx.grant) as Doc)["approvalReceiptHash"]) {
      grant["approvalReceiptHash"] = rehash;
    }
    const built = buildActionDigest(JSON.stringify(receipt), JSON.stringify(grant));
    assert.ok(built.ok, built.ok ? "" : `mutation produced an unbuildable pair: ${built.reason}`);
    return built.digest;
  }

  const cases: Array<[string, (r: Doc, g: Doc) => void]> = [
    ["tenant", (r) => { (r["scope"] as Doc)["tenant"] = "tenant-globex"; }],
    ["chain", (r) => { (r["scope"] as Doc)["chain"] = "chain-other-9"; }],
    ["actionId", (r) => { (r["action"] as Doc)["id"] = "deploy.rollback"; }],
    ["actionCanonical", (r) => { (r["action"] as Doc)["canonical"] = "deploy.apply:prod/db"; }],
    ["actionParamsHash", (r, g) => {
      const other = "sha256:" + "dd".repeat(32);
      (r["action"] as Doc)["paramsHash"] = other;
      g["paramsHash"] = other; // the grant authorizes ONE param hash; moving one without the other is refused
    }],
    ["executionGrantId", (_r, g) => { g["grantId"] = "grant-999"; }],
    ["executionNonce", (_r, g) => { g["nonce"] = "grant-nonce-99"; }],
    // THE TWO LOAD-BEARING ROWS. Each moves a field that lives in no other projection slot, so only
    // the whole-document hash can carry it.
    ["executionGrantHash (via a grant field in no other slot)", (_r, g) => {
      g["holdEnvelopeHash"] = "sha256:" + "ee".repeat(32);
    }],
    ["authorizationReceiptHash (via a receipt field in no other slot)", (r) => {
      (r["agent"] as Doc)["id"] = "approver-z";
    }],
  ];

  for (const [label, mutate] of cases) {
    assert.notEqual(mutated(mutate), baseDigest, `${label}: the digest did not move — this slot separates nothing`);
  }
});

test("domain separation: the SAME projection under any other tag is a different value", () => {
  const ctx = validContext();
  const built = buildActionDigest(JSON.stringify(ctx.receipt), JSON.stringify(ctx.grant));
  assert.ok(built.ok, built.ok ? "" : built.reason);
  const jcs = canonicalize(built.projection);
  const others = ["NOA-Receipt-v0.1-sig", "NOA-Checkpoint-v0.1-sig", "NOA-ExecGrant-v0.1-sig", "NOA-ActionDigest-v0.1-sig"];
  for (const tag of others) {
    assert.notEqual(sha256Prefixed(signingMessage(tag, jcs)), built.digest, `tag ${tag} collided`);
  }
  // And the untagged hash — what an implementation that forgot domain separation would emit.
  assert.notEqual(sha256Prefixed(jcs), built.digest, "the untagged hash equals the digest: the tag is not applied");
});

test("determinism: the digest does not depend on JSON key order or on repeated calls", () => {
  const ctx = validContext();
  const a = buildActionDigest(JSON.stringify(ctx.receipt), JSON.stringify(ctx.grant));
  const b = buildActionDigest(JSON.stringify(ctx.receipt), JSON.stringify(ctx.grant));
  assert.ok(a.ok && b.ok);
  assert.equal(a.digest, b.digest);
  // Re-serialize the grant with reversed key order: JCS must absorb it.
  const grant = ctx.grant as Record<string, unknown>;
  const reversed: Record<string, unknown> = {};
  for (const k of Object.keys(grant).reverse()) reversed[k] = grant[k];
  const c = buildActionDigest(JSON.stringify(ctx.receipt), JSON.stringify(reversed));
  assert.ok(c.ok, c.ok ? "" : c.reason);
  assert.equal(c.digest, a.digest, "key order changed the digest — the construction is not canonical");
});

test("the builder and the verifier agree: the built digest is the one the verifier accepts", () => {
  const ctx = validContext();
  const built = buildActionDigest(JSON.stringify(ctx.receipt), JSON.stringify(ctx.grant));
  assert.ok(built.ok, built.ok ? "" : built.reason);
  const res = verifyActionDigest(
    JSON.stringify({ spec: ACTION_DIGEST_SPEC, digest: built.digest }),
    JSON.stringify(ctx),
  );
  assert.equal(res.ok, true, res.ok ? "" : res.reason);
});

/**
 * THE HONEST LIMIT, PINNED AS A TEST RATHER THAN LEFT AS A SENTENCE.
 *
 * `docs/action-digest-spec.md` §6 says a digest match is not an authentication and that a relying
 * party MUST verify both documents first. A sentence in a document is not a control, and the next
 * person to read this module will read the code. So the limit is MEASURED here: a fully forged
 * authorization — attacker's own key, a receipt asserting a HUMAN-APPROVED `wire.transfer`, and a
 * grant whose signature is 64 zero bytes — is ACCEPTED by this module, and is REFUSED by the
 * kernel's own `verifyChain` the moment an honest keyring is applied.
 *
 * Two things follow, and both are why the test asserts the acceptance rather than hiding it:
 *   - the precondition in §6 is load-bearing, not boilerplate;
 *   - if anyone ever adds signature verification here, THIS TEST FAILS and forces the spec's §6 to
 *     be rewritten in the same commit. A limit that can be silently closed is a document that can
 *     silently go stale.
 */
test("HONEST LIMIT: a forged pair is ACCEPTED here and REFUSED by verifyChain (§6 precondition)", () => {
  const evil = generateKeyPair("victim-gate-1"); // the attacker's key, claiming the victim's kid
  const forged = buildReceipt(
    {
      id: "rcpt_forged",
      ts: "2026-07-14T11:55:00.000Z",
      scope: { tenant: "tenant-acme", chain: "chain-acme-1" },
      agent: { id: "approver-a", model: null, principal: "HUMAN" },
      action: {
        id: "wire.transfer",
        canonical: "wire.transfer:attacker-acct",
        riskClass: "HIGH",
        paramsHash: "sha256:" + "99".repeat(32),
        reversible: false,
        rollbackRef: null,
      },
      governance: {
        mode: "on",
        verdict: "ALLOWED",
        ruleId: "human-approved",
        approval: { by: "HUMAN:cfo@victim.example", at: "2026-07-14T11:55:00.000Z" },
        sandboxed: false,
      },
    },
    null,
    { kid: evil.kid, privateKey: evil.privateKey },
  );
  const grant = {
    spec: "noa.execution-grant/0.1",
    grantId: "grant-forged",
    holdId: "hold-forged",
    paramsHash: forged.action.paramsHash,
    holdEnvelopeHash: "sha256:" + "00".repeat(32),
    approvalReceiptHash: sha256Prefixed(receiptHashInput(forged)),
    issuedAt: "2026-07-14T11:55:00.000Z",
    expiresAt: "2026-07-14T12:30:00.000Z",
    maxUses: 1,
    nonce: "forged-nonce",
    sig: { alg: "ed25519", kid: "victim-gate-1", value: Buffer.alloc(64).toString("base64") },
  };

  const built = buildActionDigest(JSON.stringify(forged), JSON.stringify(grant));
  assert.ok(built.ok, built.ok ? "" : built.reason);
  const accepted = verifyActionDigest(
    JSON.stringify({ spec: ACTION_DIGEST_SPEC, digest: built.digest }),
    JSON.stringify({ receipt: forged, grant, expect: { tenant: "tenant-acme", chain: "chain-acme-1" } }),
  );
  assert.equal(
    accepted.ok,
    true,
    "this module now refuses a forged pair — that is an IMPROVEMENT, and docs/action-digest-spec.md §6 must be rewritten in the same commit",
  );
  assert.equal(accepted.ok && accepted.classification, "ACTION_DIGEST_LINKAGE_MATCHED");

  // THE MITIGATION, measured in the same test so the pair is never separated.
  const honest = generateKeyPair("victim-gate-1"); // the REAL gate key under the same kid
  const verdict = verifyChain(JSON.stringify([forged]), {
    keyring: JSON.stringify({ "victim-gate-1": honest.publicKey }),
  });
  assert.notEqual(verdict.status, "VALID", "the forged receipt survived the kernel's own chain verifier");
  assert.equal(verdict.signaturesVerified, false);
  assert.match(verdict.reason ?? "", /invalid signature/, "refused, but not for the signature reason §6 relies on");
});

test("an expired grant still digests, deliberately — a correlation key must not decay", () => {
  const ctx = validContext();
  const grant = JSON.parse(JSON.stringify(ctx.grant)) as Record<string, unknown>;
  grant["expiresAt"] = "2020-01-01T00:00:00.000Z";
  const built = buildActionDigest(JSON.stringify(ctx.receipt), JSON.stringify(grant));
  // Expiry is the GRANT verifier's job (`verifyArtifact` + `mustBeAfter`). If the digest refused an
  // expired grant, every audit lookup would stop matching the day the grant timed out — a
  // correlation key that decays correlates nothing. It is still a DIFFERENT value, because
  // `expiresAt` is inside the grant document that `executionGrantHash` covers.
  assert.ok(built.ok, built.ok ? "" : built.reason);
  const original = buildActionDigest(JSON.stringify(ctx.receipt), JSON.stringify(ctx.grant));
  assert.ok(original.ok);
  assert.notEqual(built.digest, original.digest);
});

test("nothing throws: hostile bytes yield a refusal, never an exception", () => {
  const hostile = [
    "",
    "null",
    "[]",
    "{",
    '{"spec":"noa.action-digest/0.1"}',
    '"sha256:' + "0".repeat(64) + '"',
    " ",
  ];
  for (const h of hostile) {
    const res = verifyActionDigest(h, h);
    assert.equal(res.ok, false, `hostile input accepted: ${JSON.stringify(h)}`);
    assert.equal(typeof res.reason, "string");
  }
});
