// Generates the NOA COSE_Sign1 -19 envelope that the foreign-stack verifier consumes.
//
// Was `_cose-interop-check.mjs` at the repository root, where the `_*.mjs` ignore rule kept it
// untracked — so the vector it produces was in the repository and the code that produces it was
// not. An artifact whose generator is missing cannot be regenerated, only trusted; both halves
// are tracked now.
//
// Run from the repository root, after `npm run build`:
//   node conformance/cose-3rd-party/gen-vector.mjs
// The key is generated fresh on every run, so the vector's signature bytes change each time.
// That is fine — nothing pins them; the Python side verifies whatever it is handed.
import { generateKeyPair } from "../../dist/src/keys.js";
import { coseSign1, coseSign1Verify } from "../../dist/src/cose/cose-sign1.js";
import { createPublicKey } from "node:crypto";
import { writeFileSync } from "node:fs";

const kid = "noa-interop-kid-1";
const kp = generateKeyPair(kid);

const payload = Buffer.from(JSON.stringify({ hello: "noa", n: 42 }), "utf8");
const cose = coseSign1(payload, { kid, privateKey: kp.privateKey });

// Sanity: our own verifier round-trips before we hand anything to a foreign stack.
//
// The keyring is serialised, not passed as an object. `coseSign1Verify` takes `Uint8Array | string`
// since the 0.6.0 bytes-in migration — the trust root a signature is judged against is a document,
// and a caller-owned object can be mutated after the check reads it. Passing the object here is how
// this script had been broken since 0.6.0 shipped: it was untracked scratch, so nothing ran it and
// nothing reported it, and the vector sitting in the repository could no longer be regenerated by
// the code in the repository. An artifact whose generator does not run is not evidence.
const keyring = JSON.stringify({ [kid]: kp.publicKey });
const self = coseSign1Verify(cose, keyring);
if (!self.ok) throw new Error("self-verify failed: " + self.reason);

// raw 32-byte Ed25519 public key (for python cryptography) — strip SPKI DER wrapper
const pubDer = Buffer.from(kp.publicKey, "base64");
const rawPub = createPublicKey({ key: pubDer, format: "der", type: "spki" })
  .export({ type: "spki", format: "der" });
// Ed25519 SPKI is 44 bytes; the raw key is the trailing 32 bytes.
const rawPub32 = rawPub.subarray(rawPub.length - 32);

// Resolved against THIS FILE, not the working directory. The header tells you to run this from
// the repository root, and a bare relative path would then drop the vector at the root — which is
// exactly the top-level clutter that moving these three files into a directory was meant to end.
const OUT = new URL("cose-sign1-ed25519.vector.json", import.meta.url);

writeFileSync(
  OUT,
  JSON.stringify(
    {
      kid,
      alg_expected: -19,
      cose_sign1_hex: cose.toString("hex"),
      protected_header_hex: "a10132", // {1:-19} canonical
      payload_hex: payload.toString("hex"),
      pub_spki_b64: kp.publicKey,
      pub_raw32_hex: rawPub32.toString("hex"),
    },
    null,
    2
  )
);

console.log("NOA self-verify:", self.ok, "kid:", self.kid);
console.log("COSE_Sign1 -19 envelope hex:", cose.toString("hex"));
console.log("protected header bytes (expect a10132 = {1:-19}):", cose.toString("hex").slice(cose.toString("hex").indexOf("a10132")));
console.log("wrote", OUT.pathname);
