/**
 * `noa.encrypted-display/0.1` — the D15-v2 encrypted approval display (build spec §8/§9/§12).
 *
 * This is the REAL sealer/opener the gate injects (the gate itself never reimplements HPKE — KURAL 5;
 * it only BINDS the sealed object via the Hold Envelope's `displayCiphertextHash`, F2). It replaces
 * the earlier structural stub: the human-readable display is genuinely HPKE-AEAD encrypted to the
 * approver device key(s) and can only be read on a device holding the matching X25519 secret.
 *
 * SCHEMA IS FROZEN (build spec §8 — do NOT add fields):
 *   { spec, tenant, holdId, deferredReceiptHash, expiresAt,
 *     suite:{kem,kdf,aead},
 *     payload:{ nonce, ciphertext },              // ONE display blob under a random CEK
 *     recipients:[ { kid, enc, wrappedCek } ],    // CEK HPKE-wrapped per registered device
 *     aadHash }                                   // AAD binds tenant‖holdId‖deferredReceiptHash‖expiresAt
 *
 * Construction (multi-recipient hybrid / envelope encryption):
 *   1. AAD = JCS({tenant,holdId,deferredReceiptHash,expiresAt}); aadHash = "sha256:"+SHA256(AAD).
 *   2. CEK = 32 random bytes; payload = ChaCha20Poly1305(CEK, random 12-byte nonce, AAD).encrypt(JCS(display)).
 *   3. per recipient: HPKE-SealBase(recipientPubKey, info=spec, aad=AAD, pt=CEK) → { enc, wrappedCek }.
 * The AAD is bound into BOTH layers, so a swapped tenant/holdId/expiry breaks decryption; the WHOLE
 * object (incl. recipients[]) is covered by the gate-signed `displayCiphertextHash` (F2), so a
 * relay-added recipient breaks the envelope binding (a device added after the hold can't read it).
 *
 * Red Line 1/11: the recipient SECRET key is supplied by the caller (the device) at open time only;
 * the sealer sees public keys, never secrets, and the plaintext is returned to the caller, never
 * logged/persisted here.
 */

import { chacha20poly1305 } from "@noble/ciphers/chacha.js";
import { canonicalize } from "./jcs.js";
import { sha256Prefixed } from "./hash.js";
import { hexToBytes, base64ToBytes, bytesToBase64 } from "./bytes.js";
import { hpkeSealBase, hpkeOpenBase, hpkeRandomBytes, HPKE_SUITE } from "./hpke.js";

/** The HPKE `info` (key-schedule domain separation) for the encrypted display. */
const DISPLAY_HPKE_INFO = new TextEncoder().encode("noa.encrypted-display/0.1");
const CEK_LEN = 32; // ChaCha20Poly1305 content-encryption key
const PAYLOAD_NONCE_LEN = 12;

/** The frozen §8 wire shape. Structurally identical to the gate's `EncryptedDisplay` (which carries
 *  an index signature) so a sealed object is assignable to the gate's `DisplaySealer` return type. */
export interface EncryptedDisplay {
  spec: "noa.encrypted-display/0.1";
  tenant: string;
  holdId: string;
  deferredReceiptHash: string;
  expiresAt: string;
  suite: { kem: number; kdf: number; aead: number };
  payload: { nonce: string; ciphertext: string };
  recipients: Array<{ kid: string; enc: string; wrappedCek: string }>;
  aadHash: string;
}

export interface DisplayRecipient {
  kid: string;
  /** X25519 public key — raw lowercase hex (64 chars, the §3 wire shape) OR base64(DER SPKI). */
  hpkePublicKey: string;
}

export interface SealDisplayInput {
  tenant: string;
  holdId: string;
  deferredReceiptHash: string;
  expiresAt: string;
  /** The human-readable display object (RAW-supplied or ENFORCED-derived). Encrypted whole. */
  display: Record<string, unknown>;
  recipients: DisplayRecipient[];
  /** TEST ONLY — pin CEK/payload-nonce/ephemeral scalars for deterministic vectors. */
  deterministic?: {
    cek: Uint8Array;
    payloadNonce: Uint8Array;
    ephemeralSecretKey: Uint8Array;
  };
}

/**
 * Decode an X25519 public key from either the raw lowercase-hex wire shape (64 chars = 32 bytes, the
 * §3/D15-v2 canonical form generated by the phone) or base64(DER SPKI) (the shape node:crypto emits,
 * used by the gate's alpha trust). Fail-closed on anything else — a mis-shaped key is never guessed.
 */
export function decodeX25519PublicKey(s: string): Uint8Array {
  if (/^[0-9a-fA-F]{64}$/.test(s)) {
    return hexToBytes(s.toLowerCase());
  }
  let raw: Uint8Array;
  try {
    raw = base64ToBytes(s);
  } catch {
    throw new Error("decodeX25519PublicKey: not 32-byte hex nor base64");
  }
  if (raw.length === 32) return raw;
  // X25519 SubjectPublicKeyInfo DER = 12-byte prefix (302a300506032b656e032100) || 32-byte key.
  if (raw.length === 44) {
    const PREFIX = [0x30, 0x2a, 0x30, 0x05, 0x06, 0x03, 0x2b, 0x65, 0x6e, 0x03, 0x21, 0x00];
    for (let i = 0; i < PREFIX.length; i++) {
      if (raw[i] !== PREFIX[i]) throw new Error("decodeX25519PublicKey: bad X25519 SPKI DER prefix");
    }
    return raw.slice(12);
  }
  throw new Error(`decodeX25519PublicKey: unexpected key length ${raw.length} (want 32 raw or 44 SPKI-DER)`);
}

/** The AAD bytes + aadHash for a display (binds tenant‖holdId‖deferredReceiptHash‖expiresAt). */
function displayAad(args: { tenant: string; holdId: string; deferredReceiptHash: string; expiresAt: string }): {
  aadBytes: Uint8Array;
  aadHash: string;
} {
  const canonical = canonicalize({
    tenant: args.tenant,
    holdId: args.holdId,
    deferredReceiptHash: args.deferredReceiptHash,
    expiresAt: args.expiresAt,
  });
  return { aadBytes: new TextEncoder().encode(canonical), aadHash: sha256Prefixed(canonical) };
}

/**
 * Seal a display into a `noa.encrypted-display/0.1` object (real HPKE-AEAD). Each recipient's entry
 * carries an independent HPKE encapsulation of the shared CEK, so N devices can each decrypt the
 * single payload blob without the gate ever holding a secret key.
 */
export function sealEncryptedDisplay(input: SealDisplayInput): EncryptedDisplay {
  if (input.recipients.length === 0) {
    throw new Error("sealEncryptedDisplay: at least one recipient is required (fail-closed; never ship plaintext)");
  }
  const { aadBytes, aadHash } = displayAad(input);

  const cek = input.deterministic ? input.deterministic.cek : hpkeRandomBytes(CEK_LEN);
  const nonce = input.deterministic ? input.deterministic.payloadNonce : hpkeRandomBytes(PAYLOAD_NONCE_LEN);
  if (cek.length !== CEK_LEN) throw new Error(`sealEncryptedDisplay: CEK must be ${CEK_LEN} bytes`);
  if (nonce.length !== PAYLOAD_NONCE_LEN) throw new Error(`sealEncryptedDisplay: payload nonce must be ${PAYLOAD_NONCE_LEN} bytes`);

  // Encrypt the WHOLE display (always) under the CEK, AAD-bound.
  const displayBytes = new TextEncoder().encode(canonicalize(input.display));
  const ciphertext = chacha20poly1305(cek, nonce, aadBytes).encrypt(displayBytes);

  // Wrap the CEK to each device via HPKE.
  const recipients = input.recipients.map((r) => {
    const pk = decodeX25519PublicKey(r.hpkePublicKey);
    const sealed = hpkeSealBase({
      recipientPublicKey: pk,
      info: DISPLAY_HPKE_INFO,
      aad: aadBytes,
      plaintext: cek,
      ...(input.deterministic ? { ephemeralSecretKey: input.deterministic.ephemeralSecretKey } : {}),
    });
    return { kid: r.kid, enc: bytesToBase64(sealed.enc), wrappedCek: bytesToBase64(sealed.ciphertext) };
  });

  return {
    spec: "noa.encrypted-display/0.1",
    tenant: input.tenant,
    holdId: input.holdId,
    deferredReceiptHash: input.deferredReceiptHash,
    expiresAt: input.expiresAt,
    suite: { kem: HPKE_SUITE.kem, kdf: HPKE_SUITE.kdf, aead: HPKE_SUITE.aead },
    payload: { nonce: bytesToBase64(nonce), ciphertext: bytesToBase64(ciphertext) },
    recipients,
    aadHash,
  };
}

export interface OpenRecipient {
  kid: string;
  /** Raw 32-byte X25519 secret key — the device key. Stays on device (Red Line 1). */
  secretKey: Uint8Array;
}

function isRecord(v: unknown): v is Record<string, unknown> {
  return typeof v === "object" && v !== null && !Array.isArray(v);
}
function asStr(v: unknown): string {
  if (typeof v !== "string") throw new Error("openEncryptedDisplay: malformed encrypted-display (expected string field)");
  return v;
}

/**
 * Open a `noa.encrypted-display/0.1` object with the device's X25519 secret key → the plaintext
 * display. Fail-closed at every step: wrong spec/suite, aadHash mismatch (tampered tenant/hold
 * binding), no recipient entry for this device, or any AEAD tag failure (wrong key / tampered
 * ciphertext) throws — there is no partial-plaintext path.
 */
export function openEncryptedDisplay(ed: unknown, recipient: OpenRecipient): Record<string, unknown> {
  if (!isRecord(ed)) throw new Error("openEncryptedDisplay: encrypted-display is not an object");
  if (ed["spec"] !== "noa.encrypted-display/0.1") throw new Error("openEncryptedDisplay: unexpected spec");

  const suite = ed["suite"];
  if (!isRecord(suite) || suite["kem"] !== HPKE_SUITE.kem || suite["kdf"] !== HPKE_SUITE.kdf || suite["aead"] !== HPKE_SUITE.aead) {
    throw new Error("openEncryptedDisplay: unsupported HPKE suite (decrypter never guesses)");
  }

  // Recompute + verify the AAD binding (tenant‖holdId‖deferredReceiptHash‖expiresAt).
  const { aadBytes, aadHash } = displayAad({
    tenant: asStr(ed["tenant"]),
    holdId: asStr(ed["holdId"]),
    deferredReceiptHash: asStr(ed["deferredReceiptHash"]),
    expiresAt: asStr(ed["expiresAt"]),
  });
  if (ed["aadHash"] !== aadHash) throw new Error("openEncryptedDisplay: aadHash does not bind the display fields (tampered)");

  const recipientsRaw = ed["recipients"];
  if (!Array.isArray(recipientsRaw)) throw new Error("openEncryptedDisplay: missing recipients[]");
  const mine = recipientsRaw.find((r): r is Record<string, unknown> => isRecord(r) && r["kid"] === recipient.kid);
  if (!mine) throw new Error(`openEncryptedDisplay: no recipient entry for kid ${recipient.kid} (device added after this hold, or wrong device)`);

  // 1. HPKE-open the wrapped CEK with the device secret key.
  const cek = hpkeOpenBase({
    recipientSecretKey: recipient.secretKey,
    enc: base64ToBytes(asStr(mine["enc"])),
    info: DISPLAY_HPKE_INFO,
    aad: aadBytes,
    ciphertext: base64ToBytes(asStr(mine["wrappedCek"])),
  });

  // 2. AEAD-open the display payload under the recovered CEK.
  const payload = ed["payload"];
  if (!isRecord(payload)) throw new Error("openEncryptedDisplay: missing payload");
  const plaintext = chacha20poly1305(cek, base64ToBytes(asStr(payload["nonce"])), aadBytes).decrypt(base64ToBytes(asStr(payload["ciphertext"])));

  const parsed = JSON.parse(new TextDecoder().decode(plaintext)) as unknown;
  if (!isRecord(parsed)) throw new Error("openEncryptedDisplay: decrypted display is not a JSON object");
  return parsed;
}
